services:
  adonis:
    container_name: adonis
    image: flapi/backend:develop
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3555:3555'
    depends_on:
      - db_mariadb
      - phpmyadmin
    networks:
      - app-network

  db_mariadb:
    container_name: db_mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flapi_develop
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - '3308:3306'
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db_mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '7450:80'
    networks:
      - app-network

networks:
  app-network:

volumes:
  database_data:
  app:
  node_modules:
